platform :ios, '7.0'
target 'Calendar' do
pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'JPush'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'Qiniu'
pod 'AMapLocation'
pod 'AMapSearch'
pod 'AMap3DMap'
pod 'SMSSDK'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/ReducedWeChat'
pod ‘UMengUShare/Social/ReducedQQ'
pod 'ProgressHUD'
pod 'MLEmojiLabel'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCAnalytics'
pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'

end
